[[language]]
name = "toml"
auto-format = true
# https://github.com/bd82/toml-tools/tree/master/packages/prettier-plugin-toml
formatter = { command = "prettier", args = ["--parser", "toml"] }

[[language]]
name = "c"
formatter = { command = "clang-format", args = ["--assume-filename", "%file"] }

[[language]]
name = "json"
formatter = { command = "prettier", args = ["--parser", "json"] }

[[language]]
name = "javascript"
auto-format = true

[[language]]
name = "python"
auto-format = true

[language-server.pylsp.config.pylsp]
plugins.ruff.enabled = true
plugins.black.enabled = true

[[language]]
name = "typescript"
auto-format = true

[[language]]
name = "markdown"
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"]}

[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rs|rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
shebangs = ["rust-script", "cargo"]
auto-format = true
comment-tokens = ["//", "///", "//!"]
block-comment-tokens = [
  { start = "/*", end = "*/" },
  { start = "/**", end = "*/" },
  { start = "/*!", end = "*/" },
]
language-servers = [ "rust-analyzer" ]
indent = { tab-width = 4, unit = "    " }
persistent-diagnostic-sources = ["rustc", "clippy"]

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = true
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false

[[language]]
name = "go"
config = { "formatting.gofumpt" = true }

[[language]]
name = "yaml"
indent = { tab-width = 0, unit = "  " }
formatter = { command = "prettier", args = ["--parser", "yaml"] }

[[language]]
name = "d2"
scope = ""
file-types = ["d2"]
comment-token = "#"
roots = [""]
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "d2"
source = { git = "https://git.pleshevski.ru/pleshevskiy/tree-sitter-d2", rev = "eb6910126fa392b60832d834fe6640635cd35ba8" }

[[language]]
name = "svelte"
auto-format = true
config = { svelte = { plugin = { svelte = { format = { config = { "svelteIndentScriptAndStyle" = false } } } } } }

[[language]]
name = "typst"
auto-fomat = true
formatter.command = "typstyle"

# ---
# [[language]]
# name = "go"
# language-servers = ["gopls", "golangci-lint"]

[[grammar]]
name = "rust"
source = { git = "https://github.com/tree-sitter/tree-sitter-rust", rev = "1f63b33efee17e833e0ea29266dd3d713e27e321" }
